name: grab jvs and parse into stuff and fonts

on:
  workflow_dispatch:
  schedule:
    - cron: 30 18 * * 5

jobs:
  jvs-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: fetch, parse
        run: cd scripts; cargo run

      - name: create pr
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: weekly jvs/font update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: jvs-update
          delete-branch: true
          title: 'weekly jvs/font update'
          assignees: berrymot
          reviewers: berrymot